### PR TITLE
Fix base URI and make year non-hardcoded

### PR DESCRIPTION
**Pull request by djvdorp**

### CODE REVIEW

**Comment by cobalamin** [comment]
But it's the drip downloader 2014 :<
Just like a 1981 DeLorean will always be a 1981 DeLorean even when you fix it :D

**Comment by cobalamin** [comment]
A bit more seriously, bumping it to 2016 makes more sense, with all the changes.

A very important discussion to have, I know.

**Comment by djvdorp** [comment]
Since you are the author, it is your pick if you want the second commit also, it was just something that crossed my mind, haha. But the first commit you'll definitely want I think!

**Comment by cobalamin** [comment]
I wish, but I can't selectively merge commits in a PR on GitHub...

**Pull request closed without merging**
